version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]
  environment = ["nodejs"]

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[code_formatters]]
name = "isort"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "standardjs"